### ISSUE TITLE
Characterize resonance frequency

### ISSUE THREAD

**Issue by jEfEpdx** [tjgilbert/ece411#11]
Test different wire garages/ and N turns per type.

**Comment by tjgilbert** [comment]
L (uH) = r^2 \* n^2 / (8 \* r + 11 \* w)
where:
r = radius to center of windings in inches
w = width of windings (in inches)
n = number of turns

[Harold A. Wheeler, "Simple Inductance Formulas for Radio Coils," Proceedings of the I.R.E., October 1928, pp. 1398-1400.](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=1669896)

**Comment by tjgilbert** [comment]
125kHz
